apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
data:
  git-sync: |
    #!/bin/bash
    cd /wiki && {{ .Values.gollum.syncCommand }}
  config.rb: |
    {{- .Values.gollum.config | nindent 4 }}
